modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/Sv3r/CuteHermitCrabs/issues"

[[mods]]
modId="cutehermitcrabs"
version="2.0.2-1.18.2"
displayName="Cute Hermit Crabs"
#updateJSONURL=""
displayURL="https://github.com/Sv3r/CuteHermitCrabs"
logoFile="logo.png"
logoBlur=false
#credits=""
authors="Sv3r"
description="Cute Hermit Crabs is a mod that adds hermit crabs and other related features."
#itemIcon=""
#configBackground=""

[[dependencies.cutehermitcrabs]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cutehermitcrabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
